disabled_rules:
  - colon
  - comma
  - fallthrough
  - force_cast
  - function_parameter_count
  - line_length
  - nesting
  - trailing_whitespace
  - unused_optional_binding
  - void_return
  - xctfail_message
  - large_tuple
  - identifier_name

opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - empty_count
  - explicit_init
  - first_where
  - literal_expression_end_indentation
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - single_test_class
  - sorted_first_last
  - strict_fileprivate
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

excluded:
  - Pods
  - GithubBrowser/Generated
